apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      labels:
        app: service-b
    spec:
      containers:
      - name: service-b
        image: rodrigordavila/service-b:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/hello
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/hello
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: service-b
  namespace: demo
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: service-b 