apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
    release: kiali
data:
  config.yaml: |
    external_services:
      prometheus:
        url: http://prometheus-kube-prometheus-prometheus.monitoring:9090
      grafana:
        url: http://prometheus-grafana.monitoring:80
    auth:
      strategy: anonymous 