apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrddevops/istio-servicemesh.git
    targetRevision: HEAD
    path: k8s/service-a
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: service-b
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rrddevops/istio-servicemesh.git
    targetRevision: HEAD
    path: k8s/service-b
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true 